### ISSUE TITLE
logout dropdown not working

### ISSUE THREAD

**Issue by nihsaan7** [Enspirer/PML#16]
![Capture8](https://user-images.githubusercontent.com/85348653/147802828-bbca66d5-f7c6-4623-b78b-4a6cafd609b3.JPG)

**Comment by prasadbanuka** [comment]
![image](https://user-images.githubusercontent.com/84589746/147832549-27b9c706-97f3-4638-b763-8252e76c6483.png)
logout dropdown fixed
